
IMDB_MOVIE_ID_FIELD = 'tconst'
IMDB_ACTOR_ID_FIELD = 'nconst'

# IMDB title.basics.tsv fields
IMDB_TITLE_BASICS_MOVIE_ID_FIELD = IMDB_MOVIE_ID_FIELD
IMDB_TITLE_BASICS_MOVIE_TYPE_FIELD = 'titleType'
IMDB_TITLE_BASICS_MOVIE_NAME_FIELD = 'primaryTitle'

# IMDB title.basics.tsv movie types
IMDB_MOVIE_TITLE_TYPES = ['movie']

# IMDB title.principals.tsv fields
IMDB_TITLE_PRINCIPALS_MOVIE_ID_FIELD = IMDB_MOVIE_ID_FIELD
IMDB_TITLE_PRINCIPALS_ACTOR_ID_FIELD = IMDB_ACTOR_ID_FIELD
IMDB_TITLE_PRINCIPALS_JOB_CATEGORY_FIELD = 'category'

IMDB_ACTOR_JOB_CATEGORIES = ['actor']

# IMDB name.basics.txt fields
IMDB_NAME_BASICS_ACTOR_ID_FIELD = IMDB_ACTOR_ID_FIELD
IMDB_NAME_BASICS_ACTOR_NAME_FIELD = 'primaryName'

