FROM neo4j:2025.07.1
LABEL authors="Daniel Rottner"

RUN mkdir -p /scripts

# Install curl in the container
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY neo4j/scripts/init/initialize_db.sh /scripts/initialize_db.sh

COPY ./neo4j/conf/neo4j.conf /var/lib/neo4j/conf/neo4j.conf
