
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    command: uvicorn bacondistance.api.main:app --host 0.0.0.0 --port 80 ${ENVIRONMENT_OPTS}
    ports:
      - "${HOST_WEB_API_PORT}:80"
    env_file:
      - .env.${ENV}
    restart: unless-stopped
